Проверка условия module1-task2.
htmlacademy-php/1418251-yeticave-12 pull request #2
Opened 2020-05-08 08:19 UTC by andrewk990

Проверка условия module1-task2.

2020-05-11 09:04 UTC, nkolosov requested changes

2020-05-11 09:04 UTC, nkolosov commented on index.php
> +        <?php if ($is_auth == 1) : ?>
1. Хромает форматирование (отступы на разных строках разные)
2. Сравнение нужно делать строго-типизированным (использовать оператор `===`)

2020-05-11 09:04 UTC, nkolosov commented on index.php
> +    		<p>#user_name#</p>
В задании сказано, что вместо этой строки нужно вывести значение переменной

2020-07-13 18:07 UTC, andrewk990 commented
Исправление замечаений к ПР:
- Хромают отступы, сместил div в условии.
- Строго-типизированное сравнение, выяснил для чего, поставил, намотал на ус =)
- Заменить вывод на переменную: выполнил, спасибо, буду стараться внимательнее читать задание.
- Readme.md добавил информацию о кураторе, ИФ, ссылку на профиль.

2020-07-14 07:43 UTC, merged